# Vault CSI SecretProviderClass配置
# 此资源定义从Vault获取Cloudflare凭证的方式
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass | default "cloudflare-vault-provider" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # 指定使用Vault CSI Provider
    secrets-store.csi.x-k8s.io/provider: vault
spec:
  provider: vault
  secretObjects:
    # 可选：将凭证同步到Kubernetes Secret
    # - data:
    #     - key: cloudflare_email
    #       objectName: cloudflare_email.txt
    #     - key: cloudflare_api_key
    #       objectName: cloudflare_api_key.txt
    #   secretName: cloudflare-credentials
    #   type: Opaque
  parameters:
    # Vault服务器地址
    vaultAddress: {{ .Values.vaultAddress | default "http://192.168.2.50:8200" | quote }}
    # Vault认证方式：kubernetes
    vaultAuthMethod: "kubernetes"
    # Kubernetes认证角色
    roleName: {{ .Values.vaultK8sRole | default "cloudflare-app-role" | quote }}
    # 服务账户令牌路径
    kubernetesServiceAccountTokenPath: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    # 要挂载的Secret配置
    objects: |
      - objectName: "cloudflare_email.txt"
        secretPath: "secret/data/MY_CLOUDFLARE_EMAIL"
        secretKey: "email"
        filePath: "cloudflare_email.txt"
      - objectName: "cloudflare_api_key.txt"
        secretPath: "secret/data/MY_CLOUDFLARE_API_KEY"
        secretKey: "api_key"
        filePath: "cloudflare_api_key.txt"