{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  # 使用显式配置的服务账户名称，如果未设置则使用应用全名
  name: {{ default (include "example-app.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}